### ISSUE TITLE
tensorflow,tf-addons,keras version

### ISSUE THREAD

**Issue by darcula1993** [sabaridsn/Facial-Attribute-Recognition-from-face-images#1]
I do meet problem when load the pretrained weight in demo.py. Which version of tf-addons and keras you use to create this weight?

Thank you very much!

**Comment by dsabarinathan** [comment]
@darcula1993  , Sorry for the late reply. 

I have used tensorflow-addons-0.16.1 for training the model.  while loading the model ,you can mention compile is false, you will not get any errors. 
`model = tf.keras.models.load_model("./model.h5",compile=False) 
`
