### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Xinyi-Ning** [sabaridsn/Facial-Attribute-Recognition-from-face-images#3]
Hello, I encountered this issue while running demo.py and would like to ask how you can solve it？
Traceback (most recent call last):
  File "demo.py", line 26, in <module>
    height,width,channel = img.shape
![image](https://github.com/dsabarinathan/Facial-Attribute-Recognition-from-face-images/assets/117429119/bfccd719-0ebe-49bb-b7a3-fd6c45352351)

**Comment by dsabarinathan** [comment]
@Xinyi-Ning , Did you give the correct video path?

**Comment by dsabarinathan** [comment]
@Xinyi-Ning , use this script for testing with a web camera.

https://github.com/dsabarinathan/Facial-Attribute-Recognition-from-face-images/blob/main/realtime_testing.py

**Comment by Xinyi-Ning** [comment]
That's all worked out now. Thank you
